// Everything that runs *inside* the sandbox: the prompt handed to Claude Code,
// and the deterministic bash wrapper that clones the repo, runs the agent,
// guarantees a commit is pushed, opens the PR, and comments back on the issue.
//
// All egress from the wrapper (git, GitHub API) goes through the Worker proxy
// authenticated with only the per-run RUN_TOKEN — never a real credential.

export function agentPrompt(issueNumber: number): string {
  return [
    "You are an autonomous software engineer working in the current directory,",
    "which is a freshly cloned Git repository on a new feature branch.",
    "",
    "1. Read the issue context in /workspace/ISSUE.md.",
    "2. Explore the repository to understand the relevant code.",
    `3. Implement the minimal, focused change that resolves issue #${issueNumber}.`,
    "4. Stage and commit your work with a clear, conventional commit message.",
    "",
    "Do not attempt to configure credentials or remotes; that is already handled.",
    "The surrounding wrapper will push your branch and open the Pull Request,",
    "so focus on producing a correct, well-scoped commit.",
  ].join("\n");
}

// Deterministic wrapper: clone via the proxy, run Claude Code, then guarantee
// a branch is pushed and a PR is opened even if the agent stopped at committing.
// It also comments back on the issue with progress and the final result.
export function runScript(): string {
  return `#!/bin/bash
set -uo pipefail

GH_API="\${PROXY_BASE}/proxy/gh-api"

# Post a comment on the triggering issue via the gh-api egress proxy.
# The real GitHub token is injected by the Worker; only RUN_TOKEN is used here.
post_comment() {
  jq -n --arg body "$1" '{body:$body}' \\
    | curl -sS -X POST "\${GH_API}/repos/\${GITHUB_REPOSITORY}/issues/\${ISSUE_NUMBER}/comments" \\
        -H "Authorization: Bearer \${RUN_TOKEN}" \\
        -H "Accept: application/vnd.github+json" \\
        -H "Content-Type: application/json" \\
        --data @- > /dev/null || echo "comment post failed"
}

post_comment "🤖 On it — spinning up an isolated sandbox and asking Claude Code to work on this issue. I'll follow up with a pull request."

git config --global user.name "issue-resolver[bot]"
git config --global user.email "issue-resolver[bot]@users.noreply.github.com"

# Route all github.com git traffic through the Worker egress proxy, and supply
# the per-run token as the credential. The real GitHub token is injected by the
# Worker and never exists inside this container.
git config --global url."\${PROXY_BASE}/proxy/github/".insteadOf "https://github.com/"
git config --global credential.helper store
PROXY_HOST=$(printf '%s' "\${PROXY_BASE}" | sed -E 's#^https?://##')
printf 'https://x-access-token:%s@%s\\n' "\${RUN_TOKEN}" "\${PROXY_HOST}" > ~/.git-credentials
chmod 600 ~/.git-credentials

cd /workspace
if ! git clone "https://github.com/\${GITHUB_REPOSITORY}.git" repo; then
  post_comment "❌ I couldn't clone the repository. Please check my access and try again."
  exit 1
fi
cd repo

BRANCH="issue-resolver/issue-\${ISSUE_NUMBER}"
git checkout -b "\${BRANCH}"

# Run Claude Code headlessly. It reads the issue and edits + commits the code.
# Capture its final summary so we can report it back on the issue.
claude -p "$(cat /workspace/PROMPT.txt)" --dangerously-skip-permissions > /workspace/claude_out.txt 2>&1 || echo "claude exited non-zero"
cat /workspace/claude_out.txt
CLAUDE_SUMMARY="$(head -c 3000 /workspace/claude_out.txt)"

# Safety net: ensure everything is committed and pushed.
git add -A
git commit -m "fix: resolve issue #\${ISSUE_NUMBER}" || echo "nothing to commit"

AHEAD=$(git rev-list --count "\${DEFAULT_BRANCH}..\${BRANCH}" 2>/dev/null || echo 0)
if [ "\${AHEAD}" = "0" ]; then
  post_comment "⚠️ Claude Code did not produce any code changes for this issue, so there is nothing to open a PR for.

<details><summary>Claude Code output</summary>

\\\`\\\`\\\`
\${CLAUDE_SUMMARY}
\\\`\\\`\\\`
</details>"
  exit 0
fi

if ! git push -u origin "\${BRANCH}"; then
  post_comment "❌ I made changes but failed to push the branch \\\`\${BRANCH}\\\`."
  exit 1
fi

# Open the PR through the gh-api egress proxy (real token injected by Worker).
PR_TITLE="$(cat /workspace/pr_title.txt)"
PR_BODY="Automated fix for issue #\${ISSUE_NUMBER}, generated by Claude Code.

Closes #\${ISSUE_NUMBER}."
PR_RESP=$(jq -n --arg t "\${PR_TITLE}" --arg h "\${BRANCH}" --arg b "\${DEFAULT_BRANCH}" --arg body "\${PR_BODY}" \\
  '{title:$t, head:$h, base:$b, body:$body}' \\
  | curl -sS -X POST "\${GH_API}/repos/\${GITHUB_REPOSITORY}/pulls" \\
      -H "Authorization: Bearer \${RUN_TOKEN}" \\
      -H "Accept: application/vnd.github+json" \\
      -H "Content-Type: application/json" \\
      --data @-)
PR_URL=$(printf '%s' "\${PR_RESP}" | jq -r '.html_url // empty')

if [ -n "\${PR_URL}" ]; then
  post_comment "✅ I opened a pull request with a proposed fix: \${PR_URL}

**What I changed:**

\${CLAUDE_SUMMARY}"
else
  # A PR may already exist for this branch; surface whatever the API returned.
  ERR=$(printf '%s' "\${PR_RESP}" | jq -r '.errors[0].message // .message // "unknown error"')
  post_comment "⚠️ I pushed the branch \\\`\${BRANCH}\\\` but could not open a pull request: \${ERR}"
fi

echo "done"
`;
}
